name: CI
on:
   workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      - 
        name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      -
        name: Cargo cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Start dependency services
        run: docker compose up -d
      -
        name: Install dev dependencies
        run: nix-shell --command "make dev-dependencies"
      -
        name: Run tests
        run: nix-shell --command "make test"

  dist:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv5te-unknown-linux-musleabi
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      - 
        name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      -
        name: Cargo cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-dist-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Install dev dependencies
        run: nix-shell --command "make dev-dependencies"
      -
        name: Build distributables
        run: nix-shell --command "make dist-${{ matrix.target }}"
      -
        name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-upload
          path: |
            dist
